### PR TITLE
Fix single checkbox implementation on horizontal form

### PR DESCRIPTION
**Pull request by ifaniqbal**

### CODE REVIEW

**Comment by dwightwatson** [comment]
Hey, thanks for this PR but it is out-of-date with the latest changes on `master`.

The `$this->horizontalForm` property has been replaced with a `$this->type` property and there is now an offset class attribute.

**Comment by ifaniqbal** [comment]
Okay. Thanks.

**Comment by ifaniqbal** [comment]
When do you plan to tag new version that include newest commit?

**Comment by dwightwatson** [comment]
My plan is to fix this issues with checkboxes/radio buttons this week and then tag 1.0.0 as there are breaking changes. 

I went through on the weekend to fix up a lot of the outstanding issues and that's why so much has changed. Not much left to go.

**Comment by ifaniqbal** [comment]
Okay. I leave it to you than. Thank you :smile:

**Comment by dwightwatson** [comment]
I've tagged `1.0.0` now with checkbox and radio support for horizontal forms. :smile:

**Comment by ifaniqbal** [comment]
Incredible. Very nice works! :smiley:

**Pull request closed without merging**
