### PR TITLE
Fix validation with array input fields

### PR DESCRIPTION
**Pull request by SystemF**
It was just as simple to remove the brackets. Works like a charm!

### CODE REVIEW

**Comment by dwightwatson** [comment]
Do you need to replace the brackets in the getFieldErrorsClass() method as well, considering it calls getFieldErrors which accounts for the brackets?

**Comment by SystemF** [comment]
You're right, it works with both of them, with or without. But I think it's better when only remove the brackets from the getFieldError() method. Can you discard that change...or do you need a new pull request? Thanks!!

**Comment by dwightwatson** [comment]
Yeah, only performing the change in `getFieldError()` is probably better, no repetition. I can't disregard that change as I only have the option to merge the pull request as is. Either just revert the changes to `getFieldErrorsClass()` in another commit to this PR or create a new one. Thanks!

**Comment by SystemF** [comment]
I think you can merge now :)

**Pull request merged**
