### PR TITLE
Fix Radio Boxes with value of zero

### PR DESCRIPTION
**Pull request by hodaEdrob**
This is to check if the value of a radio box is zero to accept it as a value and not use the label for value, only use label for value when no value is set and the value is not zero

### CODE REVIEW

**Comment by hodaEdrob** [comment]
You are correct! That is much much better! Thank you :)

**Comment by dwightwatson** [comment]
Cool - if you're able to make that change I'll merge this into master. I'm away from a computer at the moment so I won't be able to tag a new release until tomorrow.

**Comment by hodaEdrob** [comment]
I have changed the pull request, thank you.

**Comment by hodaEdrob** [comment]
Thanks a lot! Tested it locally and it works perfectly!

**Pull request merged**
